trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
      persistCredentials: true
    displayName: 'Checkout Repository'

  - script: |
      pip install -U "huggingface_hub[cli]"
    displayName: 'Install Hugging Face CLI'
  
  - script: |
      make deploy HF=$(HF)
    displayName: 'Deploy to Hugging Face'
    env:
      HF: $(HF) 

