trigger: none
 
      #- main

pr:
  branches:
    include:
      - main

stages: 
  - stage: 'Build'
    displayName: 'Build Application and Updating PR'
    jobs:
    - job: Job_Building
      displayName: 'Builing Application'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self
          persistCredentials: true
          fetchDepth: 0
          displayName: 'Checkout Repository'
        
        - script: |
            npm install -g @dvcorg/cml
          displayName: 'Install CML'

        - script: |
            make install
          displayName: 'Install Packages'

        - script: |
            make format
          displayName: 'Format Code'

        - script: |
            make train
          displayName: 'Train Model'

        - script: |
            make eval
          env:
            REPO_TOKEN: $(GITHUB_TOKEN)
          displayName: 'Evaluation & Package Artifacts'

        - script: |
            make update-branch USER_NAME="$(USER_NAME)" USER_EMAIL="$(USER_EMAIL)" GITHUB_CONNECTION_USERNAME="$(GITHUB_CONNECTION_USERNAME)" GITHUB_TOKEN="$(GITHUB_TOKEN)"
          displayName: 'Updating Current PR Branch'
          

        - task: PublishMarkdownReports@1
          inputs:
            contentPath: $(Build.SourcesDirectory)
            indexFile: report.md

        - script: |
          displayName: 'Update Branch'
          env:
            USER_NAME: $(USER_NAME)
            USER_EMAIL: $(USER_EMAIL)
            GITHUB_TOKEN: $(GITHUB_TOKEN)
            GITHUB_CONNECTION_USERNAME: $(GITHUB_CONNECTION_USERNAME)

  - stage: SAST
    displayName: 'Security and Code Analysis'
    jobs:
      - job: sonar_analysis
        displayName: 'SonarCloud Analysis'
        pool:
          vmImage: 'ubuntu-latest'

        steps:

          - checkout: self
            persistCredentials: true
            displayName: 'Checkout Repository'

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
            displayName: 'Use Python 3.x'

          - script: |
              make install
              pip install pytest pytest-cov
              pip install seaborn
            displayName: 'Installing Dependencies'

          - script: |
              python test_basic.py
            displayName: 'Running Basic Code Test using Pytest'

          - script: |
              curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
              unzip sonar-scanner.zip -d $HOME
              export PATH=$HOME/sonar-scanner-5.0.1.3006-linux/bin:$PATH
              sonar-scanner \
                -Dsonar.projectKey=arid1182_CICD-for-Machine-Learning \
                -Dsonar.organization=arid1182 \
                -Dsonar.sources=. \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.token=$(SONAR_TOKEN) \
                -Dsonar.python.version=3.8 \
                -Dsonar.python.coverage.reportPaths=coverage.xml \
                -Dsonar.exclusions=**/venv/**,**/.git/**,**/__pycache__/**
            displayName: "Run SonarCloud Analysis"

          - script: |
              pytest --cov=. --cov-report=xml -v
            displayName: 'Run Tests with Coverage'
          
          - task: SonarCloudAnalyze@1
            displayName: 'Running SonarCloud Analysis'
          
          - task: SonarCloudPublish@1
            displayName: 'Publishing Quality Gate Result'