trigger: none
 
      #- main

pr:
  branches:
    include:
      - main

# Manual trigger also supported
# In Azure DevOps, "workflow_dispatch" equivalent is "Run Pipeline" button in UI.

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
    displayName: 'Checkout Repository'
  
  - script: |
      npm install -g @dvcorg/cml
    displayName: 'Install CML'

  - script: |
      make install
    displayName: 'Install Packages'

  - script: |
      make format
    displayName: 'Format Code'

  - script: |
      make train
    displayName: 'Train Model'

  - script: |
      cml comment create report.md --repo "$(Build.Repository.Name)" --commit "$(Build.SourceVersion)" --token "$(System.AccessToken)" --driver azure-devops
   
    
  - script: |
    displayName: 'Update Branch'
    env:
      USER_NAME: $(USER_NAME)
      USER_EMAIL: $(USER_EMAIL)
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      GITHUB_CONNECTION_USERNAME: $(GITHUB_CONNECTION_USERNAME)
      run: make update-branch USER_NAME=$USER_NAME USER_EMAIL=$USER_EMAIL

    
